### ISSUE TITLE
How to use it with Google meet or Zoom?

### ISSUE THREAD

**Issue by MangalamPalod** [misbah4064/backgroundRemoval#2]
I have been trying to use this program with Video conferencing applications. But didnt succeed. If you could help, that would be appreciated.

**Comment by ghost** [comment]
Try presenting your screen

**Comment by ghost** [comment]
OR there is a [new option](https://www.howtogeek.com/698633/how-to-use-virtual-backgrounds-in-google-meet/) in google meet,with that you can use **background images** in google meet

**Comment by MangalamPalod** [comment]
I wanted to try it with manual code. But I think running the cam on double port is not possible. I think some node programming is required for this.
